### ISSUE TITLE
Introduce start_tstamp in events_this_run / events_staged

### ISSUE THREAD

**Issue by awoehrl** [snowplow/data-models#113]
Hi!
I like the idea of having start_tstamp as a consistent tstamp column in the new web model. I realize start_tstamp is just a renamed derived_tstamp, but since events_staged is one of the entry points for custom models, maybe it would make sense to include start_tstamp as a column there as well?

Best
Andreas

**Comment by colmsnowplow** [comment]
My 2c: 

So the `events_staged` table is basically a subset of the `atomic.events` table - which is essentially an unopinionated log of events as they were recorded. (We do some work to extract data into `events_staged` that's less accessible in `events`, but conceptually we don't change what the data represents).

Since events generally represent things that happen at a particular moment in time, I don't think they can have start timestamps really. Each row in the table represents a single instance in time.

For the other tables, we're aggregating over those events, combining many of those single moments in time with our logic (and the assumptions that are built into that), and each row represents some more abstract concept - which pretty much means that we've chunked the data into some period of user activity, in order to interpret the data in terms that make some business sense.

I guess the best way to articulate this is that a page view event basically represents the start of a page view. We don't have an event that represents the end of the page view, but we have page pings and we make assumptions about when we reckon it ended. 

---

That, at least is how I conceptualise it - but I think we should always be open to adapting our thinking, especially if there's some practical aspect that our principles get in the way of.

Did you have any particular use case in mind, or some way in which you envisaged using a start timestamp in the `events_staged` table?

**Comment by awoehrl** [comment]
Thanks for your insightful reply @colmsnowplow! The reasoning behind it totally makes sense and it's probably best to keep it this way.

I found myself renaming derived_tstamp to start_tstamp in all custom models I've created based on the events_staging tables. So I was wondering if it should be already added upstream in the model. I'm using the start_tstamp for events as well just to keep it simple, but you're right and basically it's a bit of a hack as events are more of a moment in time.
