### ISSUE TITLE
Model fails to run when an event has no page view id

### ISSUE THREAD

**Issue by aidanradford** [snowplow/data-models#25]
This line of code:

https://github.com/snowplow/data-models/blob/master/web/v1/redshift/sql-runner/sql/standard/01-base/01-main/10-commit-base.sql#L26

Should also contain a where clause.

WHERE page_view_id IS NOT NULL

Otherwise the model can fail on this step.

**Comment by colmsnowplow** [comment]
Covered in this issue: https://github.com/snowplow/data-models/issues/20

We'll be releasing a fix for this soon!

Closing as duplicate. Thanks for flagging! :)

**Comment by colmsnowplow** [comment]
For completeness as it might be helpful @aidanradford - the solution we're aiming for is slightly different. It's to allow Base not have the value, but filter for it in page views. 

Reason being that 
a) one might have server-side events to do custom stuff with, and it's a pain to require both session id and page view id to do so, 

and 

b) the ideal end state of the base module is a generic module for incremental logic - so ideally base isn't constrained by anything atomic.events is constrained by (even though current implementation does in fact constrain it to having a domain_sessionid - this is a pragmatic decision we made rather than a principled one, ideally we evolve away from it).
