### ISSUE TITLE
BigQuery Mobile: Fix column order in events_this_run to allow for events_staged table migration

### ISSUE THREAD

**Issue by bill-warner** [snowplow/data-models#99]
The `commit_table` procedure is not adding new columns in the atomic events table to the `events_staged` table despite the automigrate flag being set to `true`. This is due to the `event_index_in_session` field in `events_this_run` table [occurring at the end of the table](https://github.com/snowplow/data-models/blob/847a2e686978e79bfed195d212d7676a6fe7f36d/mobile/v1/bigquery/sql-runner/sql/standard/01-base/01-main/06-events-this-run.sql#L175) rather than the start.

**Comment by colmsnowplow** [comment]
I would've expected it to throw an error rather than succeed without adding the column. So if the latter is happening then we should look into that. But also:

I _think_ it's not workable to have this column occur at the end with the currently designed control flow, because the order of columns matter and the preceding columns can change...

Consider that I may run the model wehn the last two columns are `unstruct_event_foo`, `contexts_bar`. I run the model, resulting in events staged ending with `unstruct_event_foo`, `contexts_bar`, `event_index_in_session`.

Then, I add a column `unstruct_event_baz`. Now, my staged table ends in `unstruct_event_foo`, `contexts_bar`, `event_index_in_session`, but my this_run table ends in `unstruct_event_foo`, `contexts_bar`,  `unstruct_event_baz`, `event_index_in_session`. Because it's computed in the model I'm not sure there's a manageable way to have `commit_table` know where to put it. 

So, to accommodate this kind of requirement we must either a) release a breaking change to put `event_index_in_session` somewhere else, or b) change the control structures in `commit_table` to, for example, match the order of the destination table.


I'm not opposed to b) really, but I would highlight the reasoning behind the design we'd be changing: It seems quite easy to make a mistake in an update to a model, which adds a column to a derived table accidentally. It also seems easy to lose track of what column comes from where, if you're allowed add them into the middle of the source table. So, the procedure enforces that any table being automigrated must be an exact match of the destination table, except for columns to be migrated which must occur at the end of the column list.

That may be too restrictive for sure, we went conservative to begin with. Hope that context is useful.

**Comment by colmsnowplow** [comment]
Oh I see by the edited title that you may have arrived at the context I provided without my input.  Shout if you need anything :)
